modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
[[mods]]
modId = "commpr"
version = "${file.jarVersion}"
displayName = "Call of Minecart: Modern Powered Rails"
authors = "smibii"
description = '''

'''
[[dependencies.commpr]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.commpr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
ref = "commpr.mixins.json"